apiVersion: v1
kind: Service
metadata:
  name: helpdesk
  namespace: helpdesk
  labels:
    app: helpdesk
spec:
  selector:
    app: helpdesk

  type: LoadBalancer

  ports:
    - name: http
      port: 8081
      targetPort: 8080
      protocol: TCP